version: "3.8"

services:
  glpi-api:
    build: .
    container_name: glpi-api
    env_file:
      - .env
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    networks:
      - glpi_network
      
networks:
  glpi_network:
    driver: bridge